/*
 * Copyright 2022 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v12.0
processor: MIMXRT1176xxxxx
package_id: MIMXRT1176DVMAA
mcu_data: ksdk2_0
processor_version: 12.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: R17, peripheral: FLEXIO2, signal: 'IO, 10', pin_signal: GPIO_AD_10, software_input_on: Disable, pull_up_down_config: Pull_Down, pull_keeper_select: Keeper,
    open_drain: Disable, drive_strength: High, slew_rate: Slow}
  - {pin_num: P16, peripheral: FLEXIO2, signal: 'IO, 11', pin_signal: GPIO_AD_11, software_input_on: Disable, pull_up_down_config: Pull_Down, pull_keeper_select: Keeper,
    open_drain: Disable, drive_strength: High, slew_rate: Slow}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_B2_09_GPIO8_IO19,0U);		//SLP1_N
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_B2_10_GPIO8_IO20,0U);		//SLP2_N

  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_B2_00_GPIO8_IO10,0U);		//LED_0
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_B2_01_GPIO8_IO11,0U);		//LED_1
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_B2_02_GPIO8_IO12,0U);		//LED_2
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_B2_03_GPIO8_IO13,0U);		//LED_3


  IOMUXC_SetPinMux(
  	  IOMUXC_GPIO_AD_02_LPUART8_TXD,          /* GPIO_AD_24 is configured as LPUART1_TXD */
  	  0U);                                    /* Software Input On Field: Input Path is determined by functionality */

  IOMUXC_SetPinMux(
  	  IOMUXC_GPIO_AD_03_LPUART8_RXD,          /* GPIO_AD_25 is configured as LPUART1_RXD */
  	  0U);                                    /* Software Input On Field: Input Path is determined by functionality */

  IOMUXC_SetPinMux(
  	  IOMUXC_GPIO_AD_04_FLEXIO2_D04,          /* GPIO_AD_10 is configured as FLEXIO2_D04 LIN2_TX */
  	  0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
  	  IOMUXC_GPIO_AD_05_FLEXIO2_D05,          /* GPIO_AD_11 is configured as FLEXIO2_D05 LIN2_RX */
  	  0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
  	  IOMUXC_GPIO_AD_24_LPUART1_TXD,          /* GPIO_AD_24 is configured as LPUART1_TXD */
  	  0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
  	  IOMUXC_GPIO_AD_25_LPUART1_RXD,          /* GPIO_AD_25 is configured as LPUART1_RXD */
  	  0U);                                    /* Software Input On Field: Input Path is determined by functionality */

//  IOMUXC_SetPinMux(
//  	  IOMUXC_GPIO_AD_00_FLEXIO2_D00,          /* GPIO_AD_10 is configured as FLEXIO2_D04 LOG_TX */
//  	  0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//  	  IOMUXC_GPIO_AD_01_FLEXIO2_D01,          /* GPIO_AD_11 is configured as FLEXIO2_D05 LOG_RX */
//  	  0U);                                    /* Software Input On Field: Input Path is determined by functionality */


  IOMUXC_SetPinConfig(
  	  IOMUXC_GPIO_AD_04_FLEXIO2_D04,          /* GPIO_AD_10 PAD functional properties : */
  	  0x02U);                                 /* Slew Rate Field: Slow Slew Rate
  												 Drive Strength Field: high drive strength
  												 Pull / Keep Select Field: Pull Disable, Highz
  												 Pull Up / Down Config. Field: Weak pull down
  												 Open Drain Field: Disabled
  												 Domain write protection: Both cores are allowed
  												 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
  	  IOMUXC_GPIO_AD_05_FLEXIO2_D05,          /* GPIO_AD_11 PAD functional properties : */
  	  0x02U);                                 /* Slew Rate Field: Slow Slew Rate
  												 Drive Strength Field: high drive strength
  												 Pull / Keep Select Field: Pull Disable, Highz
  												 Pull Up / Down Config. Field: Weak pull down
  												 Open Drain Field: Disabled
  												 Domain write protection: Both cores are allowed
  												 Domain write protection lock: Neither of DWP bits is locked */
//  IOMUXC_SetPinConfig(
//  	  IOMUXC_GPIO_AD_00_FLEXIO2_D00,          /* GPIO_AD_10 PAD functional properties : */
//        0x02U);                                 /* Slew Rate Field: Slow Slew Rate
//  											 Drive Strength Field: high drive strength
//  											 Pull / Keep Select Field: Pull Disable, Highz
//  											 Pull Up / Down Config. Field: Weak pull down
//  											 Open Drain Field: Disabled
//  											 Domain write protection: Both cores are allowed
//  											 Domain write protection lock: Neither of DWP bits is locked */
//  IOMUXC_SetPinConfig(
//  	  IOMUXC_GPIO_AD_01_FLEXIO2_D01,          /* GPIO_AD_11 PAD functional properties : */
//        0x02U);                                 /* Slew Rate Field: Slow Slew Rate
//  											 Drive Strength Field: high drive strength
//  											 Pull / Keep Select Field: Pull Disable, Highz
//  											 Pull Up / Down Config. Field: Weak pull down
//  											 Open Drain Field: Disabled
//  											 Domain write protection: Both cores are allowed
//  											 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
  	  IOMUXC_GPIO_AD_24_LPUART1_TXD,          /* GPIO_AD_24 PAD functional properties : */
  	  0x02U);                                 /* Slew Rate Field: Slow Slew Rate
  											   Drive Strength Field: high drive strength
  											   Pull / Keep Select Field: Pull Disable, Highz
  											   Pull Up / Down Config. Field: Weak pull down
  											   Open Drain Field: Disabled
  											   Domain write protection: Both cores are allowed
  											   Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
  	  IOMUXC_GPIO_AD_25_LPUART1_RXD,          /* GPIO_AD_25 PAD functional properties : */
  	  0x02U);                                 /* Slew Rate Field: Slow Slew Rate
  											   Drive Strength Field: high drive strength
  											   Pull / Keep Select Field: Pull Disable, Highz
  											   Pull Up / Down Config. Field: Weak pull down
  											   Open Drain Field: Disabled
  											   Domain write protection: Both cores are allowed
  											   Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
  	  IOMUXC_GPIO_AD_02_LPUART8_TXD,          /* GPIO_AD_02 PAD functional properties : */
  	  0x02U);                                 /* Slew Rate Field: Slow Slew Rate
  													 Drive Strength Field: high drive strength
  													 Pull / Keep Select Field: Pull Disable, Highz
  													 Pull Up / Down Config. Field: Weak pull down
  													 Open Drain Field: Disabled
  													 Domain write protection: Both cores are allowed
  													 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
  	  IOMUXC_GPIO_AD_03_LPUART8_RXD,          /* GPIO_AD_03 PAD functional properties : */
  	  0x02U);                                 /* Slew Rate Field: Slow Slew Rate
  													 Drive Strength Field: high drive strength
  													 Pull / Keep Select Field: Pull Disable, Highz
  													 Pull Up / Down Config. Field: Weak pull down
  													 Open Drain Field: Disabled
  													 Domain write protection: Both cores are allowed
  													 Domain write protection lock: Neither of DWP bits is locked */
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
